name: CI

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sdk-publish]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
  packages: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 25.9.0

      - name: Setup npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo '@plaidev:registry="https://npm.pkg.github.com"' >> .npmrc

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build docs
        run: |
          pnpm clean
          pnpm gen
          pnpm build
          ls -lart docs

      - name: Publish docs
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          branch: main
          file_pattern: "docs/**"
          commit_message: "docs: updates"
